spring:
  application:
    name: test_project

  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/test_project}
    username: ${DB_USERNAME:test_project}
    password: ${DB_PASSWORD:test_project}

  jpa:
    hibernate:
      ddl-auto: create
#      ddl-auto: update
    show-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

